# top level stuff you probably don't need to touch
highlighter: pygments
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://dweisz.github.io/
baseurl: /
title: Dan Weisz
author: Dan Weisz
description: Homepage
avatar: profile.png
email: dweisz@uw.edu
github: dweisz
twitter: bigticketdw
google_analytics: UA-69770503-1
